#!/usr/bin/env python3
# Part of PieCoin educational project by SweetPalma, 2017. All rights reserved.
NANOCOIN_DIFFICULTY = 5
NANOCOIN_ENCODING = 'utf-8'
NANOCOIN_EXPONENT = 65537
NANOCOIN_REWARD = 50
NANOCOIN_LENGTH = 40
NANOCOIN_HASH = 'md5'
NANOCOIN_PORT = 2309
NANOCOIN_RANGE = (NANOCOIN_PORT, NANOCOIN_PORT + 100)
